name: Deploy SaaS

on:
push:
branches:
- plan   # chạy khi push vào branch plan

jobs:
deploy:
runs-on: ubuntu-latest


steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Setup SSH
    run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

  - name: Add known_hosts
    run: 
      ssh-keyscan -H 1.2.3.4 >> ~/.ssh/known_hosts

  - name: Install Ansible
    run: |
      sudo apt update
      sudo apt install -y ansible

  - name: Syntax check
    run: |
      ansible-playbook --syntax-check ansible/playbooks/deploy.yml

  - name: Dry run (check mode)
    run: |
      ansible-playbook \
        -i ansible/inventories/cus01/hosts.ini \
        ansible/playbooks/deploy.yml \
        --check --diff

